### ISSUE TITLE
Possible segfault during upsert while under load

### ISSUE THREAD

**Issue by satta** [pzhin/go-sophia#2]
I noticed that, when using upserts to handle lots of new data, I would occasionally end up with a segfault while executing the upsert. Here's some example code to trigger the issue (Debian buster, x86_64) https://gist.github.com/satta/ca008fd6e2bf84e80953c4427a56d8ca

Result:
```
$ ./sophia-go-test
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x499490]

goroutine 17 [running, locked to thread]:
github.com/pzhin/go-sophia.goUpsertCall(0x5, 0x0, 0x0, 0x7ff009ff9ab0, 0x7ff009ff99b0, 0x7ff009ff9b30, 0x7ff009ff99f0, 0xc4200a0018)
	/home/satta/golang/src/github.com/pzhin/go-sophia/upsert.go:51 +0xb0
github.com/pzhin/go-sophia._cgoexpwrap_882df5f1f5ec_goUpsertCall(0x7ffd00000005, 0x0, 0x0, 0x7ff009ff9ab0, 0x7ff009ff99b0, 0x7ff009ff9b30, 0x7ff009ff99f0, 0xc4200a0018)
	_cgo_gotypes.go:314 +0x75
```

I debugged a bit and apparently there seems to be a problem with passing the `index` value from `initializeSchema()` in `environment.go` to the actual callback `goUpsertCall()` in `upsert.go`, which sometimes takes seemingly random values (in the example, not equal to 0). These are dereferenced in the callback and lead to a segfault.
The [Sophia documentation](http://sophia.systems/v2.2/conf/db.html) states that the value for `db.<db>.upsert_arg` (as referenced by `keyUpsertArgTemplate`) should be a string -- so I tried that and using a string to funnel through the index for the given database fixed the issue for me. See patch below; just wanted to alert you of the problem, there may well be a better solution, but I needed something that works right now :)

```patch
diff --git a/environment.go b/environment.go
index eee1f44..0a42811 100644
--- a/environment.go
+++ b/environment.go
@@ -1,6 +1,7 @@
 package sophia
 
 import (
+       "C"
        "errors"
        "fmt"
 )
@@ -56,7 +57,7 @@ func (env *Environment) NewDatabase(config DatabaseConfig) (*Database, error) {
                        return nil, env.Error()
                }
                registerUpsertArg(index, config.UpsertArg)
-               ok = env.Set(fmt.Sprintf(keyUpsertArgTemplate, config.Name), &index)
+               ok = env.SetString(fmt.Sprintf(keyUpsertArgTemplate, config.Name), fmt.Sprintf("%d", index))
                if !ok {
                        unregisterUpsert(index)
                        return nil, env.Error()
@@ -86,14 +87,16 @@ func (env *Environment) NewDatabase(config DatabaseConfig) (*Database, error) {
 func (env *Environment) initializeSchema(name string, schema *Schema) int {
        i := 0
        var schemaPath = fmt.Sprintf("db.%s.scheme", name)
-       for n, typ := range schema.keys {
+       for _, n := range schema.keysNames {
+               typ := schema.keys[n]
                env.SetString(schemaPath, n)
                keyPath := fmt.Sprintf("db.%s.scheme.%s", name, n)
                key := fmt.Sprintf("%s,key(%d)", typ.String(), i)
                env.SetString(keyPath, key)
                i++
        }
-       for n, typ := range schema.values {
+       for _, n := range schema.valuesNames {
+               typ := schema.values[n]
                env.SetString(schemaPath, n)
                value := fmt.Sprintf("db.%s.scheme.%s", name, n)
                env.SetString(value, typ.String())
diff --git a/upsert.go b/upsert.go
index 639a5c7..0c35319 100644
--- a/upsert.go
+++ b/upsert.go
@@ -2,6 +2,7 @@ package sophia
 
 import (
        "reflect"
+       "strconv"
        "sync"
        "unsafe"
 )
@@ -45,7 +46,7 @@ func goUpsertCall(count C.int,
        upsert **C.char, upsert_size *C.uint32_t,
        result **C.char, result_size *C.uint32_t,
        arg unsafe.Pointer) {
-       index := *(*int)(arg)
+       index, _ := strconv.Atoi(C.GoString((*C.char)(arg)))
        fn := getUpsert(index)
        upsertArg := getUpsertArg(index)
        fn(count, src, src_size, upsert, upsert_size, result, result_size, upsertArg)
```

(Note: I also made a change to ensure stable field order, but that is most likely unrelated. You can just ignore that if you want.)

**Comment by pzhin** [comment]
Thanks for reporting this issue!

In sophia sources you can find such definition of upsert function.
```
typedef int (*sfupsertf)(int count,
                         char **src,    uint32_t *src_size,
                         char **upsert, uint32_t *upsert_size,
                         char **result, uint32_t *result_size,
                         void *arg);
```
So i think that it is inaccuracy in sophia documentation, because you can pass any pointer argument, not only `char*`.

Your solution is not correct. It has same problem but it shadowed by ignoring `strconv.Atoi` error. Please check it again after https://github.com/pzhin/go-sophia/commit/8bdc21833f991add161fb0053fa9818ce45c2cc8.

We pass some pointer to C code and forget about it. After GC is done, we can reuse same address for another value and when C calls upsert callback with given pointer it leads to another unexpected value.

**Comment by satta** [comment]
Ah, excellent. Thanks for the correction and for the quick fix of course!
